appName: productcatalogservice
repoUser: alexkkk21
appReplicas: 1
containerPort: 3550
serviceType: ClusterIP
servicePort: 3550
containerEnvVars:
  - name: PORT
    value: "3550"
  - name: DISABLE_PROFILER
    value: "1"
resourcesReqCpu: 100m
resourcesReqMem: 64Mi
resourcesLimCpu: 200m
resourcesLimMem: 128Mi
