---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.appNamespace }}
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: {{ .Values.appName }}
  ports:
    - name: tcp-redis
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.containerPort }}
