apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helmfile-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/AlexeyKrasnoshchekov/k8s_microservices.git" # Git репозиторий с helmfile.yaml
    targetRevision: HEAD
    path: charts # путь к каталогу с helmfile.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
