apiVersion: apps/v1
kind: Deployment
metadata:
  name: promtail
  labels:
    app: promtail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      containers:
        - name: promtail
          image: grafana/promtail:latest
          args:
            - "-config.file=/etc/promtail/config.yml"
          ports:
            - containerPort: 9080
          volumeMounts:
            - name: dock-containers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: dock-sock
              mountPath: /var/run/docker.sock
              readOnly: true
            - name: promtail-config
              mountPath: /etc/promtail/config.yml
              subPath: config.yml
      volumes:
        - name: dock-containers
          hostPath:
            path: /var/lib/docker/containers
            type: Directory
        - name: dock-sock
          hostPath:
            path: /var/run/docker.sock
            type: Socket
        - name: promtail-config
          configMap:
            name: promtail-config
      securityContext:
        privileged: true
