# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: {{ include "microservice_chart.fullname" . }}
#   labels:
#     {{- include "microservice_chart.labels" . | nindent 4 }}
# spec:
#   {{- if not .Values.autoscaling.enabled }}
#   replicas: {{ .Values.replicaCount }}
#   {{- end }}
#   selector:
#     matchLabels:
#       {{- include "microservice_chart.selectorLabels" . | nindent 6 }}
#   template:
#     metadata:
#       {{- with .Values.podAnnotations }}
#       annotations:
#         {{- toYaml . | nindent 8 }}
#       {{- end }}
#       labels:
#         {{- include "microservice_chart.labels" . | nindent 8 }}
#         {{- with .Values.podLabels }}
#         {{- toYaml . | nindent 8 }}
#         {{- end }}
#     spec:
#       {{- with .Values.imagePullSecrets }}
#       imagePullSecrets:
#         {{- toYaml . | nindent 8 }}
#       {{- end }}
#       serviceAccountName: {{ include "microservice_chart.serviceAccountName" . }}
#       {{- with .Values.podSecurityContext }}
#       securityContext:
#         {{- toYaml . | nindent 8 }}
#       {{- end }}
#       containers:
#         - name: {{ .Chart.Name }}
#           {{- with .Values.securityContext }}
#           securityContext:
#             {{- toYaml . | nindent 12 }}
#           {{- end }}
#           image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
#           imagePullPolicy: {{ .Values.image.pullPolicy }}
#           ports:
#             - name: http
#               containerPort: {{ .Values.service.port }}
#               protocol: TCP
#           {{- with .Values.livenessProbe }}
#           livenessProbe:
#             {{- toYaml . | nindent 12 }}
#           {{- end }}
#           {{- with .Values.readinessProbe }}
#           readinessProbe:
#             {{- toYaml . | nindent 12 }}
#           {{- end }}
#           {{- with .Values.resources }}
#           resources:
#             {{- toYaml . | nindent 12 }}
#           {{- end }}
#           {{- with .Values.volumeMounts }}
#           volumeMounts:
#             {{- toYaml . | nindent 12 }}
#           {{- end }}
#       {{- with .Values.volumes }}
#       volumes:
#         {{- toYaml . | nindent 8 }}
#       {{- end }}
#       {{- with .Values.nodeSelector }}
#       nodeSelector:
#         {{- toYaml . | nindent 8 }}
#       {{- end }}
#       {{- with .Values.affinity }}
#       affinity:
#         {{- toYaml . | nindent 8 }}
#       {{- end }}
#       {{- with .Values.tolerations }}
#       tolerations:
#         {{- toYaml . | nindent 8 }}
#       {{- end }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "microservice_chart.fullname" . }}
  labels:
    {{- include "microservice_chart.labels" . | nindent 4 }}  
  # name: {{ .Values.appName }}
  # labels:
  #   app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.appReplicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      serviceAccountName: {{ .Values.appName }}
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: "{{ .Values.repUser }}:{{ .Values.appName }}"
        ports:
        - containerPort: {{ .Values.containerPort }}
        env:
        {{- range .Values.containerEnvVars}}
        - name: {{ .key }}
          value: {{ .value | quote }}
        {{- end}}
        # resources:
        #   requests:
        #     cpu: 200m
        #     memory: 180Mi
        #   limits:
        #     cpu: 300m
        #     memory: 300Mi
        # readinessProbe:
        #   initialDelaySeconds: 20
        #   periodSeconds: 15
        #   grpc:
        #     port: 9555
        # livenessProbe:
        #   initialDelaySeconds: 20
        #   periodSeconds: 15
        #   grpc:
        #     port: 9555
